import { Router } from 'express';
import { requireAuth } from '../middleware/auth.js';
import { tenantContext } from '../middleware/tenant.js';
import { auditLog } from '../middleware/audit.js';
import { validate } from '../middleware/validate.js';
import accountRouter from './account.js';
import authRouter from './auth.js';
import rulesRouter from './rules.js';
import rolesRouter from './roles.js';
import bonusRouter from './bonus.js';
import delegationsRouter from './delegations.js';
import usersRouter from './users.js';
import auditRouter from './audit.js';
import leaveRouter from './leave.js';
import appointmentsRouter from './appointments.js';
import departmentsRouter from './departments.js';
import attendanceRouter, { publicPunchRouter } from './attendance.js';
import biometricRouter from './biometric.js';
import payrollRouter from './payroll.js';
import payrollDeductionRouter from './payrollDeduction.js';
import employeesRouter from './employees.js';
import employeeSectionsRouter from './employeeSections.js';
import positionsRouter from './positions.js';
import performanceRouter from './performance.js';
import plantillaRouter from './plantilla.js';
import vacancyRouter from './vacancy.js';
import designationRouter from './designation.js';
import trainingRouter from './training.js';
import recruitmentRouter from './recruitment.js';
import essRouter from './ess.js';
import loansRouter from './loans.js';
import reportsRouter from './reports.js';
import databaseRouter from './database.js';
import tenantsRouter from './tenants.js';
import disqualificationsRouter from './disqualifications.js';
import integrationsRouter from './integrations.js';
import integrationRequestsRouter from './integrationRequests.js';

const router = Router();

router.use('/auth', authRouter);
router.use('/integrations', integrationsRouter);
router.use('/integrations/requests', integrationRequestsRouter);
// Public biometric punch - no JWT required
router.use('/attendance/public-punch', publicPunchRouter);
router.use('/', requireAuth);
router.use('/', tenantContext);
router.use('/', auditLog);
router.use('/rules', rulesRouter);
router.use('/roles', rolesRouter);
router.use('/bonus', bonusRouter);
router.use('/account', accountRouter);
router.use('/delegations', delegationsRouter);
router.use('/users', usersRouter);
router.use('/audit', auditRouter);
router.use('/leave', leaveRouter);
router.use('/appointments', appointmentsRouter);
router.use('/departments', departmentsRouter);
router.use('/attendance', attendanceRouter);
router.use('/biometric', biometricRouter);
router.use('/payroll', payrollRouter);
router.use('/payroll-deduction', payrollDeductionRouter);
router.use('/employees', employeesRouter);
router.use('/employees/:id/sections', employeeSectionsRouter);
router.use('/positions', positionsRouter);
router.use('/performance', performanceRouter);
router.use('/plantilla', plantillaRouter);
router.use('/vacancy', vacancyRouter);
router.use('/designation', designationRouter);
router.use('/training', trainingRouter);
router.use('/recruitment', recruitmentRouter);
router.use('/ess', essRouter);
router.use('/loans', loansRouter);
router.use('/reports', reportsRouter);
router.use('/database', databaseRouter);
router.use('/tenants', tenantsRouter);
router.use('/disqualifications', disqualificationsRouter);

export default router;
