/**
 * Single source of truth for role capabilities (permission matrix).
 *
 * Capabilities are enforced server-side via `requirePermission(...keys)`
 * (`backend/src/middleware/permission.js`) on the routes listed in each key's
 * comment. Effective permissions come from the `RolePermission` table; roles
 * with no rows fall back to `DEFAULT_PERMISSIONS` below (so brand-new tenants
 * behave like the historical role whitelist). Editing the matrix changes real
 * authorization, including for custom (non-system) roles.
 */

export const CAPABILITIES = [
  { key: 'manageUsersAndRoles', label: 'Manage users & roles' },
  { key: 'employeeRecordsCRUD', label: 'Employee records (all access)' },
  { key: 'payrollRuns', label: 'Create / generate / approve / post payroll' },
  { key: 'payrollRead', label: 'Read payroll runs, items & payslips' },
  { key: 'leaveApproval', label: 'Approve leave (dept scope)' },
  { key: 'auditTrail', label: 'View audit trail' },
  { key: 'reports', label: 'Generate reports' },
  { key: 'ess', label: 'ESS self-service' },
  { key: 'attendancePortal', label: 'Attendance portal (biometric)' },
  { key: 'appointmentsRead', label: 'View appointments' },
  { key: 'appointmentsCRUD', label: 'Manage appointments' },
  { key: 'disqualificationCRUD', label: 'Manage DIBAR records' },
  { key: 'recruitmentCRUD', label: 'Manage vacancies and applicants' },
  { key: 'interviewCRUD', label: 'Manage interviews and selection' },
  { key: 'trainingCRUD', label: 'Manage training programs and enrollments' },
  { key: 'performanceRead', label: 'View performance reviews & competencies' },
  { key: 'performanceCRUD', label: 'Manage performance reviews & competencies' },
  { key: 'loansCRUD', label: 'Manage employee loans' },
  { key: 'documentsCRUD', label: 'Manage documents (tracking & workflow)' },
  { key: 'documentsTrack', label: 'View document access & tracking log' },
];

/** route mapping (documentation only) */
export const CAPABILITY_ROUTES = {
  manageUsersAndRoles: ['/users', '/roles'],
  employeeRecordsCRUD: ['/employees', '/employees/:id/sections'],
  payrollRuns: ['/payroll/runs POST|approve|generate|post', '/payroll/periods POST|close', '/payroll-deduction writes'],
  payrollRead: ['/payroll GETs', '/payroll-deduction GET lines', 'payslip print HTML'],
  leaveApproval: ['/leave GET|PATCH', '/leave/credits', '/ess/leave-requests POST self-scoped'],
  auditTrail: ['/audit'],
  reports: ['/reports'],
  ess: ['/ess (frontend-gated, self-service)'],
  attendancePortal: ['/attendance-portal (frontend-gated, self-service)'],
  appointmentsRead: ['/appointments GET'],
  appointmentsCRUD: ['/appointments POST|PATCH|DELETE'],
  disqualificationCRUD: ['/disqualifications'],
  documentsCRUD: ['/documents POST|PATCH|DELETE|status (tracking workflow)'],
  documentsTrack: ['/documents/tracking', '/documents/:id/tracking'],
  performanceRead: ['/performance GETs (reviews, targets, review competencies)', '/performance/competencies GETs'],
  performanceCRUD: ['/performance POST|PATCH|DELETE|compute', '/performance/:id/targets writes', '/performance/:id/competencies writes', '/performance/competencies writes'],
};

/**
 * Defaults must mirror the historical backend role whitelist (the effective
 * authorization before the matrix existed). These are seed values; admins can
 * edit them. A role absent here denies everything (fail closed).
 */
export const DEFAULT_PERMISSIONS = {
  ADMIN: {
    manageUsersAndRoles: true,
    employeeRecordsCRUD: true,
    payrollRuns: true,
    payrollRead: true,
    leaveApproval: true,
    auditTrail: true,
    reports: true,
    ess: true,
    attendancePortal: true,
    appointmentsRead: true,
    appointmentsCRUD: true,
    disqualificationCRUD: true,
    recruitmentCRUD: true,
    interviewCRUD: true,
    trainingCRUD: true,
    performanceRead: true,
    performanceCRUD: true,
    loansCRUD: true,
    documentsCRUD: true,
    documentsTrack: true,
  },
  SUPER_ADMIN: {
    manageUsersAndRoles: true,
    employeeRecordsCRUD: true,
    payrollRuns: true,
    payrollRead: true,
    leaveApproval: true,
    auditTrail: true,
    reports: true,
    ess: true,
    attendancePortal: true,
    appointmentsRead: true,
    appointmentsCRUD: true,
    disqualificationCRUD: true,
    recruitmentCRUD: true,
    interviewCRUD: true,
    trainingCRUD: true,
    performanceRead: true,
    performanceCRUD: true,
    loansCRUD: true,
    documentsCRUD: true,
    documentsTrack: true,
  },
  HR_MANAGER: {
    manageUsersAndRoles: false,
    employeeRecordsCRUD: true,
    payrollRuns: false,
    payrollRead: true,
    leaveApproval: true,
    auditTrail: false,
    reports: true,
    ess: true,
    attendancePortal: true,
    appointmentsRead: true,
    appointmentsCRUD: true,
    disqualificationCRUD: true,
    recruitmentCRUD: true,
    interviewCRUD: true,
    trainingCRUD: true,
    performanceRead: true,
    performanceCRUD: true,
    loansCRUD: true,
    documentsCRUD: true,
    documentsTrack: true,
  },
  PAYROLL_OFFICER: {
    manageUsersAndRoles: false,
    employeeRecordsCRUD: false,
    payrollRuns: true,
    payrollRead: true,
    leaveApproval: false,
    auditTrail: false,
    reports: true,
    ess: true,
    attendancePortal: true,
    appointmentsRead: false,
    appointmentsCRUD: false,
    disqualificationCRUD: false,
    recruitmentCRUD: false,
    interviewCRUD: false,
    trainingCRUD: false,
    loansCRUD: false,
    documentsCRUD: false,
    documentsTrack: false,
  },
  DEPARTMENT_HEAD: {
    manageUsersAndRoles: false,
    employeeRecordsCRUD: true,
    payrollRuns: false,
    payrollRead: false,
    leaveApproval: true,
    auditTrail: false,
    reports: false,
    ess: true,
    attendancePortal: true,
    appointmentsRead: false,
    appointmentsCRUD: false,
    disqualificationCRUD: false,
    recruitmentCRUD: false,
    interviewCRUD: false,
    trainingCRUD: false,
    performanceRead: true,
    performanceCRUD: true,
    loansCRUD: false,
    documentsCRUD: false,
    documentsTrack: false,
  },
  AUDITOR: {
    manageUsersAndRoles: false,
    employeeRecordsCRUD: false,
    payrollRuns: false,
    payrollRead: false,
    leaveApproval: false,
    auditTrail: true,
    reports: true,
    ess: false,
    attendancePortal: false,
    appointmentsRead: false,
    appointmentsCRUD: false,
    disqualificationCRUD: false,
    recruitmentCRUD: false,
    interviewCRUD: false,
    trainingCRUD: false,
    performanceRead: false,
    performanceCRUD: false,
    loansCRUD: false,
    documentsCRUD: false,
    documentsTrack: true,
  },
  EMPLOYEE: {
    manageUsersAndRoles: false,
    employeeRecordsCRUD: false,
    payrollRuns: false,
    payrollRead: false,
    leaveApproval: false,
    auditTrail: false,
    reports: false,
    ess: true,
    attendancePortal: true,
    appointmentsRead: false,
    appointmentsCRUD: false,
    disqualificationCRUD: false,
    recruitmentCRUD: false,
    interviewCRUD: false,
    trainingCRUD: false,
    loansCRUD: false,
    documentsCRUD: false,
    documentsTrack: false,
  },
};